name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  
jobs:
  tests:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm package.json
      - run: mv package.test.json package.json 
      - run: yarn install
      - run: yarn typeCheck
      - run: yarn test